config/routes.rb
Rails.application.routes.draw do
  resources :franjas
  resources :productos
  resources :tipos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tipos#index'
end

app/models/producto.rb
class Producto < ApplicationRecord
	
	belongs_to :tipo
	
	validates :nombre, presence: {message: "Debe ingresar un Nombre"}
	validates :descripcion, presence: {message: "Debe ingresar una descripción"}
	validates :tipo_id, presence: {message: "Debe seleccionar un tipo"}
	validates :precio, presence: {message: "Ver acá si lo hacemos que calcule solo el precio, no hay que ponerlo requerido..."}, numericality: true
	
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
    @tipos = Tipo.all
  end


  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :tipo_id, :precio)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(producto) do |f| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2>Tenemos <%= pluralize(producto.errors.count, "error") %>, no se puede guardar este producto:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :tipo_id %>
    <%= f.select :tipo_id,  Tipo.all.collect {|t| [ t.nombre, t.id ] }, { include_blank: 'Seleccionar Tipo de Producto' } %>
  </div>
  <div class="field">
    <%= f.label :precio %>
    <%= f.number_field :precio, :step => "0.5", min: 0 %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar Producto" %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Modificar Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Ver', @producto %> |
<%= link_to 'Volver', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Tipo de Producto</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.tipo.nombre %></td>
        <td><%= producto.precio %></td>
        <td><%= link_to 'Ver', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Volver', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>
<p>
  <strong>Tipo de producto:</strong>
  <%= @producto.tipo.nombre %>
</p>
<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>
<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Volver', productos_path %>