config/routes.rb
Rails.application.routes.draw do
  resources :franjas
  resources :productos
  resources :tipos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tipos#index'
end

app/models/franja.rb
class Franja < ApplicationRecord
<<<<<<< HEAD

	validates :primera_hasta, presence: true
	validates :segunda_hasta, presence: true
	validates :primera_precio, presence: true
	validates :segunda_precio, presence: true
	validates :tercera_precio, presence: true



	validates :primera_hasta, numericality: true, numericality: { less_than: :segunda_hasta, message: "Debe ser menor a la segunda franja sueldos" }
	validates :segunda_hasta, numericality: true, numericality: { greater_than: :primera_hasta }
	validates :primera_precio, numericality: true, numericality: { less_than: :segunda_precio }
  	validates :segunda_precio, numericality: true, numericality: { greater_than_or_equal: :primera_precio, less_than: :tercera_precio }
	validates :tercera_precio, numericality: true, numericality: { greater_than: :segunda_precio }
	



=======
	fecha = DateTime.now
	validates :fecha, presence: {message: "Debe ingresar la fecha /// tmb podriamos hacer que la fecha se genere automaticamente"}
	validates :primera_hasta, numericality: true, presence: true
	validates :primera_precio, numericality: true, presence: true
	validates :segunda_hasta, numericality: true
	validates :segunda_precio, numericality: true
	validates :tercera_precio, numericality: true, presence: true
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
end

app/controllers/franjas_controller.rb
class FranjasController < ApplicationController
  before_action :set_franja, only: [:show, :edit, :update, :destroy]

  # GET /franjas
  # GET /franjas.json
  def index
    @franjas = Franja.all
  end

  # GET /franjas/1
  # GET /franjas/1.json
  def show
  end

  # GET /franjas/new
  def new
    @franja = Franja.new
  end

  # GET /franjas/1/edit
  def edit
  end

  # POST /franjas
  # POST /franjas.json
  def create
    @franja = Franja.new(franja_params)
<<<<<<< HEAD
    @franja.fecha = Time.now

    respond_to do |format|
      if @franja.save
        format.html { redirect_to @franja, notice: 'La Franja se creo correctamente.' }
=======

    respond_to do |format|
      if @franja.save
        format.html { redirect_to @franja, notice: 'La Franja se creo correctamente' }
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
        format.json { render :show, status: :created, location: @franja }
      else
        format.html { render :new }
        format.json { render json: @franja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /franjas/1
  # PATCH/PUT /franjas/1.json
  def update
    respond_to do |format|
      if @franja.update(franja_params)
<<<<<<< HEAD
        format.html { redirect_to @franja, notice: 'La Franja se modifico correctamente.' }
=======
        format.html { redirect_to @franja, notice: 'Franja was successfully updated.' }
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
        format.json { render :show, status: :ok, location: @franja }
      else
        format.html { render :edit }
        format.json { render json: @franja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /franjas/1
  # DELETE /franjas/1.json
  def destroy
    @franja.destroy
    respond_to do |format|
<<<<<<< HEAD
      format.html { redirect_to franjas_url, notice: 'La Franja se elimino correctamente.' }
=======
      format.html { redirect_to franjas_url, notice: 'Franja was successfully destroyed.' }
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_franja
      @franja = Franja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def franja_params
      params.require(:franja).permit(:fecha, :primera_hasta, :primera_precio, :segunda_hasta, :segunda_precio, :tercera_precio)
    end
end

app/helpers/franjas_helper.rb
module FranjasHelper
end

app/views/franjas/_form.html.erb
<%= form_for(franja) do |f| %>
  <% if franja.errors.any? %>
    <div id="error_explanation">
<<<<<<< HEAD
      <h2>Tenemos <%= pluralize(franja.errors.count, "error") %>, no se puede guardar esta franja:</h2>
=======
      <h2><%= pluralize(franja.errors.count, "error") %> prohibited this franja from being saved:</h2>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad

      <ul>
      <% franja.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<<<<<<< HEAD
 <!--  <div class="field">
    <%= f.label :fecha %>
    <%= f.datetime_select :fecha %>
  </div> -->

  <div class="field">
    <%= f.label "Sueldos_hasta: " %>
    <%= f.number_field :primera_hasta,min:0 %>
  </div>

  <div class="field">
    <%= f.label "Valor del ticket: " %>
    <%= f.number_field :primera_precio, min:0 %>
  </div>

  <div class="field">
    <%= f.label "Sueldos hasta: " %>
    <%= f.number_field :segunda_hasta, min:0 %>
  </div>

  <div class="field">
    <%= f.label "Valor del ticket: " %>
    <%= f.number_field :segunda_precio, min:0 %>
  </div>
  <div class="field">
    <%= f.label "Sueldos mayores: " %>
  </div>
  <div class="field">
    <%= f.label "Valor del ticket: " %>
    <%= f.number_field :tercera_precio, min:0 %>
  </div>

  <div class="actions">
    <%= f.submit "Guardar Franja" %>
=======
  <div class="field">
    <%= f.label :fecha %>
    <% f.fecha.now%>
  </div>

  <div class="field">
    <%= f.label :primera_hasta %>
    <%= f.text_field :primera_hasta %>
  </div>

  <div class="field">
    <%= f.label :primera_precio %>
    <%= f.text_field :primera_precio %>
  </div>

  <div class="field">
    <%= f.label :segunda_hasta %>
    <%= f.text_field :segunda_hasta %>
  </div>

  <div class="field">
    <%= f.label :segunda_precio %>
    <%= f.text_field :segunda_precio %>
  </div>

  <div class="field">
    <%= f.label :tercera_precio %>
    <%= f.text_field :tercera_precio %>
  </div>

  <div class="actions">
    <%= f.submit %>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
  </div>
<% end %>

app/views/franjas/edit.html.erb
<<<<<<< HEAD
<h1>Modificar Franja</h1>

<%= render 'form', franja: @franja %>

<%= link_to 'Ver', @franja %> |
<%= link_to 'Volver', franjas_path %>
=======
<h1>Editing Franja</h1>

<%= render 'form', franja: @franja %>

<%= link_to 'Show', @franja %> |
<%= link_to 'Back', franjas_path %>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad

app/views/franjas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Franjas</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
<<<<<<< HEAD
      <th>Sueldos hasta</th>
      <th>Valor del ticket</th>
      <th>Sueldos hasta</th>
      <th>Valor del ticket</th>
      <th>Sueldos mayores a</th>
      <th>Valor del ticket</th>
=======
      <th>Primera hasta</th>
      <th>Primera precio</th>
      <th>Segunda hasta</th>
      <th>Segunda precio</th>
      <th>Tercera precio</th>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @franjas.each do |franja| %>
      <tr>
<<<<<<< HEAD
        <td><%= franja.fecha.to_formatted_s(:short) %></td>
=======
        <td><%= franja.fecha %></td>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
        <td><%= franja.primera_hasta %></td>
        <td><%= franja.primera_precio %></td>
        <td><%= franja.segunda_hasta %></td>
        <td><%= franja.segunda_precio %></td>
<<<<<<< HEAD
        <td><%= franja.segunda_hasta %></td>
        <td><%= franja.tercera_precio %></td>
        <td><%= link_to 'Ver', franja %></td>
        <td><%= link_to 'Editar', edit_franja_path(franja) %></td>
        <td><%= link_to 'Eliminar', franja, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
=======
        <td><%= franja.tercera_precio %></td>
        <td><%= link_to 'Show', franja %></td>
        <td><%= link_to 'Edit', edit_franja_path(franja) %></td>
        <td><%= link_to 'Destroy', franja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<<<<<<< HEAD
<%= link_to 'Nueva Franja', new_franja_path %>
=======
<%= link_to 'New Franja', new_franja_path %>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad

app/views/franjas/new.html.erb
<<<<<<< HEAD
<h1>Nueva Franja</h1>

<%= render 'form', franja: @franja %>

<%= link_to 'Volver', franjas_path %>
=======
<h1>New Franja</h1>

<%= render 'form', franja: @franja %>

<%= link_to 'Back', franjas_path %>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad

app/views/franjas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
<<<<<<< HEAD
  <%= @franja.fecha.to_formatted_s(:short) %>
</p>

<p>
  <strong>Sueldos hasta:</strong>
=======
  <%= @franja.fecha %>
</p>

<p>
  <strong>Primera hasta:</strong>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
  <%= @franja.primera_hasta %>
</p>

<p>
<<<<<<< HEAD
  <strong>Valor del ticket:</strong>
=======
  <strong>Primera precio:</strong>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
  <%= @franja.primera_precio %>
</p>

<p>
<<<<<<< HEAD
  <strong>Sueldos mayores a </strong><%= @franja.primera_hasta %><strong> y hasta:</strong>
=======
  <strong>Segunda hasta:</strong>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad
  <%= @franja.segunda_hasta %>
</p>

<p>
<<<<<<< HEAD
  <strong>Valor del ticket:</strong>
  <%= @franja.segunda_precio %>
</p>
<p>
  <strong>Sueldos mayores a </strong><%= @franja.segunda_hasta %>
</p>
<p>
  <strong>Valor del ticket:</strong>
  <%= @franja.tercera_precio %>
</p>

<%= link_to 'Editar', edit_franja_path(@franja) %> |
<%= link_to 'Volver', franjas_path %>
=======
  <strong>Segunda precio:</strong>
  <%= @franja.segunda_precio %>
</p>

<p>
  <strong>Tercera precio:</strong>
  <%= @franja.tercera_precio %>
</p>

<%= link_to 'Edit', edit_franja_path(@franja) %> |
<%= link_to 'Back', franjas_path %>
>>>>>>> 13fe95910bd20b5b003c3292f96d3e48fe9c33ad